set-option -g status-position top # status bar at the top

unbind o # unbind the default key for session switching
unbind C-o # unbind the default key for session switching

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r L resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
bind -n S-Enter send-keys "\e[13;2u"

bind M-r source-file ~/.config/tmux/tmux.conf

